### ISSUE TITLE
Cannot compile due to paper hard fork.

### ISSUE THREAD

**Issue by andrewkm** [BG-Software-LLC/WildLoaders#118]
### Minecraft's Version

1.21.4

### Plugin's Version

https://github.com/BG-Software-LLC/WildLoaders/commit/3e68804785112dcd3681d976c1610612b9ed849e

### Describe the bug

https://pastebin.com/raw/itqFzBAA

### To Reproduce

Compile against 1.21.4 master branch (Paper) post hardfork. @OmerBenGera

**Comment by OmerBenGera** [comment]
Fixed

**Comment by andrewkm** [comment]
> Fixed

https://pastebin.com/raw/fVsWcPHP

We are still having an issue building due to it wanting JDK 16, and seeing as it's EOL it's giving us problems setting it up on our jenkins.

Can you please fix with:

https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention
