### ISSUE TITLE
Paperweight update required. Compilation failure.

### ISSUE THREAD

**Issue by andrewkm** [BG-Software-LLC/WildLoaders#133]
### Minecraft's Version

Paper 1.21.5

### Plugin's Version

N/A

### Describe the bug

Can't compile.

```
A problem occurred configuring project ':NMS:v1_21_5'.
> Failed to create service 'paperweight-userdev:setupService:03e77baa2e85fb5dbe337c7578902ef575da6f529c304b398c58ca00aae969db'.
   > Could not create an instance of type io.papermc.paperweight.userdev.internal.setup.UserdevSetup.
      > The paperweight development bundle you are attempting to use is of data version '7', but the currently running version of paperweight only supports data versions '[2, 3, 4, 5, 6]'.
```

### To Reproduce

Compile.

### Additional Information

Paper weight needs update.

**Comment by OmerBenGera** [comment]
Fixed in latest commit :)

**Comment by andrewkm** [comment]
> Fixed in latest commit :)

@OmerBenGera 
You've not pushed any commits...
Perhaps an oversight? Still broken.

**Comment by OmerBenGera** [comment]
> > Fixed in latest commit :)
> 
> [@OmerBenGera](https://github.com/OmerBenGera) You've not pushed any commits... Perhaps an oversight? Still broken.

My bad, should be pushed now

**Comment by andrewkm** [comment]
Thanks, can confirm this is now fixed.
